# WAP TO CHECK IF A NUMBER ENTERED BY THE USER IS ODD OR EVEN

# n=int(input("enter a number :"))

# if n%2==0:
#     print("Even") 
# else:
#     print("Odd")   

#

# username=(input("Enter The username :"))
# n=len(username)
# if " " in username:
#     print("Invalid Username")
# elif n<=4:
#     print("Too short")
# else:
#     print("Username Accepted ")    

# # WAP TO FIND THE GREASTEST OF 3 NUMBERS ENTERED BY USER

# user_1=input("Enter the user 1 :")
# user_2=input("Enter the user 2 :")
# user_3=input("Enter the user 3 :")

# if user_1>user_2 and user_1>user_3:
#     print("user 1 is greatest number ",user_1)
# elif user_2>user_1 and user_2>user_3:
#     print("user 2 is greatest number ", user_2)
# else:
#     print("user 3 is greastest number", user_3)       